### PR TITLE
node 0.12 support: update to mmmagic 0.3.13

### PR DESCRIPTION
**Pull request by maxme**

### CODE REVIEW

**Comment by vanng822** [comment]
Thanks @maxme 

Look like that v0.8 failed. Can you add travis to run with node v0.12

I am thinking that we maybe drop support for v0.8, ie not running test for that version. How about that?

I will out for a long run now, will be back around 2-3hrs

**Comment by vanng822** [comment]
It is ok to remove the failing assertion since one deep assertion should be enough.

But I wonder what is going on with Vows, it seems not report result

**Comment by vanng822** [comment]
And we look to have the answer
https://github.com/vowsjs/vows/issues/341

**Comment by vanng822** [comment]
Is it ok if I merge and fix the tests?

**Comment by maxme** [comment]
> Is it ok if I merge and fix the tests?

Sorry I missed that reply. Yes, it's ok, it's a tiny change, I needed this and thought other would need it too ;). BTW thanks for the lib!

**Comment by vanng822** [comment]
Thank you

I bumped minor instead of maintenance.

Now the tests passed but still failed on travis due to the http server running in background. Will fix it later since at the moment I don't have a running node environment :-(

**Comment by vanng822** [comment]
Sorry for delay, it took sometimes to fix so npm can login and publish

**Pull request merged**
